### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by phacks** [theodo/falco#24]
## Motivation

Projects with clear contribution guidelines makes it easier to get started as a contributor.

## Prior art

- https://www.gatsbyjs.org/contributing/how-to-contribute/ (probably overkill this early in the project)
- https://github.com/mui-org/material-ui/#contributing
- https://github.com/marmelab/react-admin#contributing

## Todo

- [ ] Create a `CONTRIBUTING.md` file
- [ ] Make sure that the install docs are clear, easy to follow and (most importantly) just works
- [ ] Provide better fixtures for new installs of the project
- [ ] Mention the contribution guidelines (and CoC) directly in the README

**Comment by phacks** [comment]
Closed by #62
