### ISSUE TITLE
[☂️Umbrella issue] Falco should work with private WebPageTest instances

### ISSUE THREAD

**Issue by phacks** [theodo/falco#68]
That one’s a biggie, so this issue will be used as a place to keep track of all the information pertaining to running Falco with private WPT instances.

## Motivation

There are many reasons to run you own WebPageTest instance:

- Access and audit restricted websites that are only accessible within your own network
- Credentials and audit results do not leave your own network
- No rate limiting, meaning that you can run as many audits as you want, whenever you want
- No queueing or wait times
- Reducing the load on the public instances

## Related resources

- The [WebPageTest technical wiki](https://wikitech.wikimedia.org/wiki/Performance/WebPageTest#WebPageTest_and_AWS) from the Wikimedia Foundation
- The [GitHub docs](https://github.com/WPO-Foundation/webpagetest-docs/blob/master/user/Private%20Instances/README.md) on the WebPageTest repository
- The dedicated [Slack channel](https://webperformance.herokuapp.com/) (over at `#webpagetest-instances`)
- The dedicated [WebPageTest forum](https://www.webpagetest.org/forums/forumdisplay.php?fid=12)

## Implementation plan

- [x] Deploy a private WebPageTest instance: http://webpagetest.theo.do
- [x] Run a manual audit on the private instance (_PI_)
- [x] In development, run automated audits with Falco on the PI
- [x] Decide whether using a PI should be a project-based or an instance-based setting
- [x] Integrate the available configurations from the PI to publicly available configurations
- [x] ~Do not ask for a WebPageTest API Key if audits are solely ran on a PI~ even private instances need an API Key

## Miscellaneous

- [ ] How can we whitelist Heroku’s IP adresses for the private instance?

_This section is a work in progress_

**Comment by phacks** [comment]
Private Instance support should be project-based. This entails several changes in the code:

- Project settings should have an optional “Private WebPageTest instance URL” input
- When the URL is entered (and validated), the user should check that it works by clicking on a button
- This button press should trigger a call to the backend that will:
  - Fetch available configurations by requesting `<WPT instance URL>/getLocations.php?f=json`
  - Store those configurations in the DB
  - Return them to the frontend, which should display them into the configuration select

This means that:

- The `AvailableAuditParameters` model should have a new `webpagetest_instance_url` field;
- The daily update of `AvailableAuditParameters` should take care of private instances as well
